{
 "title": "otelcol metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_version",
    "label": "service_version",
    "query": {
     "query": "query_result(sum(otelcol_process_uptime{}) by (service_version))\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Otel Collector Instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(otelcol_process_cpu_seconds{service_instance_id=~\".*\"}) by (service_instance_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "gauge",
   "description": "otelcol_process_cpu_seconds",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(otelcol_process_cpu_seconds{}[$__rate_interval])*100) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Rss",
   "type": "gauge",
   "description": "avg(otelcol_process_memory_rss{}) by (instance)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(otelcol_process_memory_rss{}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "options": {
    "content": "# Opentelemetry Collector Data Flow\n\nopentelemetry collector contrib Data Ingress/Egress metrics are in focus.\n\n`service_version:` ${service_version}\n\n"
   }
  },
  { "title": "TracingPipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Trace Signalling Pipelines",
   "type": "nodeGraph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(\n  sum by(client) (rate(otelcol_receiver_accepted_spans{}[$__interval]))\n  , \"id\", \"$0\", \"client\", \".*\")\n    , \"title\", \"$0\", \"client\", \".*\")\n        ,\"mainstat\",\"\",\"\",\"\")\n         or\n    label_replace(label_replace(label_replace(\n  sum by(service_name) (rate(otelcol_receiver_accepted_spans{}[$__interval]))\n  , \"id\", \"processor\", \"\", \"\")\n    , \"title\", \"processor\", \"\", \"\")\n    ,\"mainstat\",\"\",\"\",\"\")\n\n             or\n    label_replace(label_replace(label_replace(\n    sum by(processor) (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n      , \"id\", \"$0\", \"processor\", \".*\")\n    , \"title\", \"$0\", \"processor\", \".*\")\n    ,\"mainstat\",\"\",\"\",\"\")\n\n  or\n    label_replace(label_replace(label_replace(\n sum by(exporter) (rate(otelcol_exporter_sent_spans{}[$__interval]))\n      , \"id\", \"exporter\", \"\", \"\")\n    , \"title\", \"exporter\", \"\", \"\")\n    ,\"mainstat\",\"\",\"\",\"\")\n                 or\n    label_replace(label_replace(label_replace(\n sum by(exporter) (rate(otelcol_exporter_sent_spans{}[$__interval]))\n      , \"id\", \"$0\", \"exporter\", \".*\")\n    , \"title\", \"$0\", \"exporter\", \".*\")\n    ,\"mainstat\",\"\",\"\",\"\")\n    \n    ",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_replace(\n  sum by(client,server) (rate(otelcol_receiver_accepted_spans{}[$__interval]))\n\n ,\"source\",\"$0\",\"client\",\".*\")\n,\"target\",\"processor\",\"server\",\".*\")\n,\"id\",\"-\",\"client\",\"server\")\n\n  or\n\n  label_join(\nlabel_replace(label_replace(\n    sum by(processor,server) (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"processor\",\"\",\"\")\n,\"target\",\"$0\",\"processor\",\".*\")\n,\"id\",\"-\",\"source\",\"processor\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n    sum by(processor,server) (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"$0\",\"processor\",\".*\")\n,\"target\",\"exporter\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n    sum by(exporter) (rate(otelcol_exporter_sent_spans{}[$__interval]))\n ,\"source\",\"exporter\",\"\",\"\")\n,\"target\",\"$0\",\"exporter\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "Spans Accepted by Receiver and Transport",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total Accepted ",
   "type": "stat",
   "description": "Total Spans Accepted ",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Batch",
   "type": "stat",
   "description": "Total Batch Processed",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{}[$__rate_interval]))  by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Total Export ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "description": "Sent by Exporter",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Refused",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total Refused ",
   "type": "stat",
   "description": "Total Spans Accepted ",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total Failed Export ",
   "type": "stat",
   "description": "otelcol_exporter_send_failed_spans",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Sent by Exporter\notelcol_exporter_send_failed_spans",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  { "title": "Metrics Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Metrics Signalling Pipelines",
   "type": "nodeGraph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(\nsum by(client) (rate(otelcol_receiver_accepted_metric_points{}[$__interval]))\n, \"id\", \"$0\", \"client\", \".*\")\n, \"title\", \"$0\", \"client\", \".*\")\n,\"mainstat\",\"\",\"\",\"\")\n\nor\n\nlabel_replace(label_replace(label_replace(\nsum by(client) (rate(otelcol_receiver_accepted_metric_points{}[$__interval]))\n, \"id\", \"processor\", \"\", \"\")\n, \"title\", \"processor\", \"\", \"\")\n,\"mainstat\",\"\",\"\",\"\")\n\n\n\nor\nlabel_replace(label_replace(label_replace(\nsum by(processor) (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n, \"id\", \"$0\", \"processor\", \".*\")\n, \"title\", \"$0\", \"processor\", \".*\")\n,\"mainstat\",\"\",\"\",\"\")\n\n\n\n\n\nor\nlabel_replace(label_replace(label_replace(\nsum (rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n, \"id\", \"exporter\", \"\", \"\")\n, \"title\", \"exporter\", \"\", \"\")\n,\"mainstat\",\"\",\"\",\"\")\nor\nlabel_replace(label_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n, \"id\", \"$0\", \"exporter\", \".*\")\n, \"title\", \"$0\", \"exporter\", \".*\")\n,\"mainstat\",\"\",\"\",\"\")\n\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_replace(\nsum by(client,server) (rate(otelcol_receiver_accepted_metric_points{}[$__interval]))\n\n,\"source\",\"$0\",\"client\",\".*\")\n,\"target\",\"processor\",\"server\",\".*\")\n,\"id\",\"-\",\"client\",\"server\")\n\nor\n\nlabel_join(\nlabel_replace(label_replace(\nsum by(processor,server) (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n,\"source\",\"processor\",\"\",\"\")\n,\"target\",\"$0\",\"processor\",\".*\")\n,\"id\",\"-\",\"source\",\"processor\")\n\n\n\n\nor\nlabel_join(\nlabel_replace(label_replace(\nsum by(processor,server) (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n,\"source\",\"$0\",\"processor\",\".*\")\n,\"target\",\"exporter\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\n\n\nor\nlabel_join(\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n,\"source\",\"exporter\",\"\",\"\")\n,\"target\",\"$0\",\"exporter\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "otelcol_receiver_accepted_metric_points",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total Accepted ",
   "type": "stat",
   "description": "otelcol_receiver_accepted_metric_points",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Batc",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{}[$__rate_interval]))  by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Total Export ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "description": "Sent by Exporter",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  { "title": "Scrape (Prometheus or otelcol)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Samples Scraped",
   "type": "stat",
   "description": "scrape_samples_scraped{job!=\"\"}",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(scrape_samples_scraped{job!=\"\"}[5m]) / 300",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Prometheus Scrape",
   "type": "nodeGraph",
   "gridPos": { "h": 9, "w": 10, "x": 7, "y": 42 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"}) by (instance)\n, \"id\", \"$0\", \"instance\", \".*\")\n, \"title\", \"$0\", \"instance\", \".*\")\n,\"mainstat\",\"\",\"\",\"\")\n\nor \n\nlabel_replace(label_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"})\n, \"id\", \"prometheus\", \"\", \"\")\n, \"title\", \"prometheus\", \"\", \"\")\n,\"mainstat\",\"\",\"\",\"\")\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"}) by (instance)\n,\"source\",\"$0\",\"instance\",\".*\")\n,\"target\",\"prometheus\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Samples Scraped",
   "type": "stat",
   "description": "scrape_samples_scraped{job!=\"\"}",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(scrape_samples_scraped{job!=\"\"}[5m]) / 300",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}