{
 "title": "Spanmetrics Dashboard",
 "description": "Spanmetrics way of application view. (contact Devrim Demiroz)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(service_name)" },
   {
    "name": "operation",
    "query": "label_values({__name__=~\".*\",service_name=~\"$service\"},operation)"
   },
   { "name": "env", "query": "label_values(env)" }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "APM Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(calls_total{}[$__range])) by (operation,service_name)) "
    },
    {
     "expr": "topk(10, sum(rate(calls_total{status_code=\"STATUS_CODE_ERROR\"}[$__range])) by (operation,service_name))"
    }
   ]
  },
  {
   "title": "Services Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service_name) (rate( calls_total{service_name=~\"$service\",env=~\"$env\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Services ERROR Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate( calls_total{status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service\",env=~\"$env\"}[$__range])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  },
  {
   "title": "Service Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_bucket{service_name=~\"${service}\",env=~\"$env\"}[$__rate_interval])) by (le,service_name))",
     "legendFormat": "{{le}} - {{service_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Highest Endpoint Latencies Over Range ",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (operation,service_name)(increase(latency_sum{service_name=~\"${service}\", operation=~\"${operation}\",env=~\"$env\"}[$__rate_interval]) / increase(latency_count{service_name=~\"${service}\", operation=~\"${operation}\",env=~\"$env\"}[$__rate_interval])))",
     "legendFormat": "[{{service_name}}]  {{operation}}"
    }
   ]
  },
  {
   "title": "Latencies Over Range ",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (operation,service_name)(increase(latency_sum{service_name=~\"${service}\", operation=~\"${operation}\",env=~\"$env\"}[$__rate_interval]) / increase(latency_count{service_name=~\"${service}\", operation=~\"${operation}\",env=~\"$env\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}-{{operation}}-"
    }
   ]
  }
 ]
}