global:
  evaluation_interval: 30s
  scrape_interval: 5s
  params:
    cors_origin: ['*']
scrape_configs:
- job_name: otel
  static_configs:
  - targets:
    - 'otelcol:9464'
  params:
    cors_origin: ['*']
- job_name: otel-collector
  static_configs:
  - targets:
    - 'otelcol:8888'
  params:
    cors_origin: ['*']
