receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:12345"
exporters:
  jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  logging:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  prometheus:
    endpoint: "otelcol:9464"

  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true

processors:
  batch:
  spanmetrics:
    metrics_exporter: 'otlp'
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"

  servicegraph:
    metrics_exporter: 'otlp'
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    dimensions: [cluster, namespace]
    store:
      ttl: 2s
      max_items: 200

  metricstransform:
    transforms:
      - include: ^calls.total$$
        match_type: regexp
        action: update
        new_name: traces_spanmetrics_calls_total
        operations:
          - action: update_label
            label: operation
            new_label: span.name
      - include: ^latency_bucket$$
        match_type: regexp
        action: update
        new_name: traces_spanmetrics_latency_bucket
      - include: ^latency_count$$
        match_type: regexp
        action: update
        new_name: traces_spanmetrics_latency_count
      - include: ^latency.sum$$
        match_type: regexp
        action: update
        new_name: traces_spanmetrics_latency_sum

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [ spanmetrics,batch]
      exporters: [jaeger]
    traces/servicegraph:
      receivers: [ otlp ]
      processors: [ servicegraph ]
      exporters: [ otlp ]
    metrics/spanmetrics:
      receivers: [ otlp/spanmetrics ]
      exporters: [ otlp ]
    metrics:
      receivers: [otlp]
      processors: [metricstransform,batch]
      exporters: [prometheusremotewrite]

